trigger:
- main

pool:
  vmImage: windows-2022

name: '$(Date:%y).$(DayOfYear).$(Rev:r)'

steps:

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: 5.8.x

- task: gitversion/execute@0
  displayName: Determine Version
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml

- task: DotNetCoreCLI@2
  displayName: Restore nuget packages
  inputs:
    command: restore
    projects: src/po.sln

- task: DotNetCoreCLI@2
  displayName: Build and zip to the staging directory (linux-x64)
  inputs:
    command: publish
    projects: src/po/po.csproj
    arguments: '--no-restore --configuration Debug --runtime linux-x64 --output $(Build.ArtifactStagingDirectory)/output --no-self-contained'
    zipAfterPublish: true
    modifyOutputPath: true

- task: CopyFiles@2
  displayName: Copy deployment files to output
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/deployment/
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory)

- powershell: '"$(Build.SourceVersionMessage)" > $(Build.ArtifactStagingDirectory)/commit-desc.txt'
  displayName: Get build desc

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    publishLocation: Container
