// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using po.DataAccess;

#nullable disable

namespace po.Migrations
{
    [DbContext(typeof(PoContext))]
    [Migration("20220409174946_Blobs")]
    partial class Blobs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("po.Models.PoBlob", b =>
                {
                    b.Property<string>("AccountName")
                        .HasMaxLength(23)
                        .HasColumnType("nvarchar(23)");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<string>("Name")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.HasKey("AccountName", "ContainerName", "Name");

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("po.Models.SlashCommand", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsGuildLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresChannelEnablement")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("SuccessfullyRegistered")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("SlashCommands");
                });

            modelBuilder.Entity("po.Models.SlashCommandChannel", b =>
                {
                    b.Property<string>("SlashCommandName")
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("SlashCommandName", "ChannelId");

                    b.ToTable("SlashCommandChannels");
                });

            modelBuilder.Entity("po.Models.SynchronizedBackgroundService", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("CountExecutions")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("LastExecuted")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Name");

                    b.ToTable("SynchronizedBackgroundServices");
                });

            modelBuilder.Entity("po.Models.SlashCommandChannel", b =>
                {
                    b.HasOne("po.Models.SlashCommand", null)
                        .WithMany("EnabledChannels")
                        .HasForeignKey("SlashCommandName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("po.Models.SlashCommand", b =>
                {
                    b.Navigation("EnabledChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
